@startuml

!include Menu-Classes.iuml

SFMLMenu ..|> IState
StateSoloGame ..|> IState
StateGame ..|> IState
StateRoom ..|> IState
StateCredit ..|> IState

StateManager *-- IState

SFMLMenu o-- SFMLButton
SFMLMenu o-- SFMLTextBox
StateCredit o-- SFMLTextBox
StateRoom o-- SFMLTextBox
StateRoom o-- World
SFMLMenu o-- World
StateSoloGame o-- World
StateGame o-- World

@enduml