@startuml

!include Network-Classes.iuml

ISocketUDP ..|> ISocket
ISocketTCP ..|> ISocket
SocketUDP ..|> ISocketUDP
SocketTCP ..|> ISocketTCP
NetworkBuffer ..|> IBuffer

NetworkException --> std::exception
TCPException --> NetworkException
UDPException --> NetworkException
SelectException --> NetworkException
BufferException --> NetworkException

@enduml
