@startuml

ISocketUDP ..|> ISocket
ISocketTCP ..|> ISocket
SocketUDP ..|> ISocketUDP
SocketTCP ..|> ISocketTCP

NetworkException --> std::exception
TCPException --> NetworkException
UDPException --> NetworkException
SelectException --> NetworkException
BufferException --> NetworkException

NetworkBuffer ..> IBuffer

@enduml
