@startuml

!include NetworkRelay-Classes.iuml

ServerRelay ..|> INetworkRelay
RoomServer --|> Room

ServerRelay o-- Remote
ServerRelay o-- IBuffer
ServerRelay o-- RoomServer
RunWorldServer o-- World
RunWorldServer o-- ServerRelay
RunWorldServer o-- Timer

Room o-- Mutex

@enduml