@startuml

!include Systems-Classes.iuml

MoveSystem -up-|> ASystem
MoveSystem -up- Speed2DComponent
MoveSystem -left- Pos2DComponent
ActionFireSystem -up-|> ASystem
ActionFireSystem -up- ActionComponent
ActionFireSystem -left- EntitySpawnerComponent
ActionMovementSystem -up-|> ASystem
ActionMovementSystem -up- ActionComponent
ActionMovementSystem -up- Speed2DComponent
AttachedToSystem -up-|> ASystem
AttachedToSystem -left- AttachedToComponent
AttachedToSystem -up- Pos2DComponent
AttachSystem -up-|> ASystem
AttachSystem -left- AttachComponent
AutoDestructSystem -up-|> ASystem
AutoDestructSystem -left- AutoDestructComponent
BackgroundSystem -up-|> ASystem
BackgroundSystem -left- TagComponent
BackgroundSystem -up- Pos2DComponent
BackgroundSystem -left- SFMLSpriteComponent
CollisionSoloSystem -up-|> ASystem
CollisionSoloSystem -left- CollisionComponent
CollisionSoloSystem -up- Pos2DComponent
CollisionSoloSystem -left- Box2DComponent
CollisionSystem -up-|> ASystem
CollisionSystem -left- CollisionComponent
CollisionSystem -up- Pos2DComponent
CollisionSystem -left- Box2DComponent
DisconnectPlayerSystem -up-|> ASystem
DisconnectPlayerSystem -left- DisconnectPlayerEvent
EntityDeleterSystem -up-|> ASystem
EntityDeleterSystem -left- EntityDeletedEvent
EntitySpawnerSystem -up-|> ASystem
EntitySpawnerSystem -left- TeamComponent
EntitySpawnerSystem -up- Pos2DComponent
EntitySpawnerSystem -left- EntitySpawnerComponent
FireAlwaysSystem -up-|> ASystem
FireAlwaysSystem -up- ActionComponent
Friction2DSystem -up-|> ASystem
Friction2DSystem -left- Friction2DComponent
Friction2DSystem -up- Speed2DComponent
LifeSystem -up-|> ASystem
LifeSystem -left- LifeComponent
LifeSystem -left- EntityDeletedEvent
MoveFollowSystem -up-|> ASystem
MoveFollowSystem -left- MoveFollowComponent
MoveFollowSystem -up- ActionComponent
MoveForwardSystem -up-|> ASystem
MoveForwardSystem -left- MoveForwardComponent
MoveForwardSystem -up- ActionComponent
MovementLimitFrame2DSystem -up-|> ASystem
MovementLimitFrame2DSystem -left- MovementLimitFrame2DComponent
MovementLimitFrame2DSystem -up- Pos2DComponent
MovementLimitFrame2DSystem -left- Box2DComponent
MoveSequenceSystem -up-|> ASystem
MoveSequenceSystem -left- MoveSequenceComponent
MoveSequenceSystem -up- ActionComponent
MoveSystem -up-|> ASystem
MoveSystem -up- Speed2DComponent
MoveSystem -up- Pos2DComponent
NetworkReceiveActionSystem -up-|> ASystem
NetworkReceiveActionSystem -up- ActionComponent
NetworkReceiveActionSystem -left- NetworkReceiveActionComponent
NetworkReceiveActionSystem -left- INetworkRelay
NetworkReceiveDieEntitySystem -up-|> ASystem
NetworkReceiveDieEntitySystem -left- EntityDeletedEvent
NetworkReceiveDieEntitySystem -up- NetworkReceiveUpdateComponent
NetworkReceiveDieEntitySystem -left- INetworkRelay
NetworkReceiveUpdateSystem -up-|> ASystem
NetworkReceiveUpdateSystem -left- INetworkRelay
NetworkReceiveUpdateSystem -left- NetworkReceiveUpdateComponent
NetworkSendActionSystem -up-|> ASystem
NetworkSendActionSystem -left- INetworkRelay
NetworkSendActionSystem -left- NetworkSendActionComponent
NetworkSendActionSystem -up- ActionComponent
NetworkSendDieEntitySystem -up-|> ASystem
NetworkSendDieEntitySystem -left- INetworkRelay
NetworkSendDieEntitySystem -left- EntityDeletedEvent
NetworkSendUpdateSystem -up-|> ASystem
NetworkSendUpdateSystem -left- INetworkRelay
NetworkSendUpdateSystem -left- ASerializableComponent
NetworkTimeOutEntitySystem -up-|> ASystem
NetworkTimeOutEntitySystem -up- NetworkReceiveUpdateComponent
OutOfBoundsSystem -up-|> ASystem
OutOfBoundsSystem -up- Pos2DComponent
PlayerLifeSystem -up-|> ASystem
PlayerLifeSystem -left- EntityDeletedEvent
PowerUpSystem -up-|> ASystem
PowerUpSystem -left- EntityDeletedEvent
PowerUpSystem -left- CollisionEvent
QuadTree -up-|> ASystem
QuadTree -left- CollisionSoloSystem
ResetActionSystem -up-|> ASystem
ResetActionSystem -up- ActionComponent
ScoreSystem -up-|> ASystem
ScoreSystem -left- EntityDeletedEvent
SFMLDisplayScoreSystem -up-|> ASystem
SFMLDisplayScoreSystem -left- SFMLTextComponent
SFMLDisplayScoreSystem -left- TagComponent
SFMLDisplaySystem -up-|> ASystem
SFMLEventSystem -up-|> ASystem
SFMLInputSystem -up-|> ASystem
SFMLInputSystem -up- ActionComponent
SFMLRenderSystem -up-|> ASystem
SFMLRenderSystem -left- SFMLSpriteComponent
SFMLRenderSystem -up- Pos2DComponent
SFMLRenderTextSystem -up-|> ASystem
SFMLRenderTextSystem -left- SFMLTextComponent
SFMLRenderTextSystem -up- Pos2DComponent
SFMLSetDisplayLiveSystem -up-|> ASystem
SFMLSetDisplayLiveSystem -left- TagComponent
SFMLSetDisplayLiveSystem -left- SFMLTextComponent
SFMLSoundSystem -up-|> ASystem
SFMLSoundSystem -left- SFMLSoundComponent
SpawnPlayerSystem -up-|> ASystem
SpawnPlayerSystem -left- NetworkPlayerComponent
SpawnPlayerSystem -left- EntityFactory
SpawnPlayerSystem -left- NewPlayerEvent
SpawnPlayerSystem .down.|> IPlayerRespawner
SpawnSoloPlayerSystem -up-|> ASystem
SpawnSoloPlayerSystem -left- EntityFactory
SpawnSoloPlayerSystem .down.|> IPlayerRespawner
SyncPos2DSystem -up-|> ASystem
SyncPos2DSystem -down- SyncPos2DComponent
SyncPos2DSystem -up- Pos2DComponent
@enduml