@startuml

package Systems {

class ActionFireSystem
class ActionMovementSystem
class AttachedToSystem
class AttachSystem
class AutoDestructSystem
class BackgroundSystem
class CollisionSoloSystem
class CollisionSystem
class DisconnectPlayerSystem
class EntityDeleterSystem
class EntitySpawnerSystem
class FireAlwaysSystem
class Friction2DSystem
class IPlayerRespawner
class LifeSystem
class MoveFollowSystem
class MoveForwardSystem
class MovementLimitFrame2DSystem
class MoveSequenceSystem
class MoveSystem
class NetworkReceiveActionSystem
class NetworkReceiveDieEntitySystem
class NetworkReceiveUpdateSystem
class NetworkSendActionSystem
class NetworkSendDieEntitySystem
class NetworkSendUpdateSystem
class NetworkTimeOutEntitySystem
class OutOfBoundsSystem
class PlayerLifeSystem
class PowerUpSystem
class QuadTree
class ResetActionSystem
class ScoreSystem
class SFMLDisplayScoreSystem
class SFMLDisplaySystem
class SFMLEventSystem
class SFMLInputSystem
class SFMLRenderSystem
class SFMLRenderTextSystem
class SFMLSetDisplayLiveSystem
class SFMLSoundSystem
class SpawnPlayerSystem
class SpawnSoloPlayerSystem
class SyncPos2DSystem

}

@enduml