@startuml

!include Threads-Classes.iuml

Mutex ..|> IMutex
CondVar ..|> ICondVar
ThreadException --|> std::exception
SafeFifoException --|> std::exception

ScopedMutex o-- Mutex
Mutex o-- STATUS

CondVar -- Mutex

@enduml