@startuml

!include Threads-Classes.iuml

ThreadException ..|> std::exception
SafeFifoException ..|> std::exception
MutexException ..|> std::exception

Container ..|> IContainer

Any o-- IContainer

ICondVar -- Mutex
CondVar ..|> ICondVar
CondVar -- MutexException

Task ..|> ITask
Task -- Any

CTask ..|> ITask

Thread ..|> IThread
Thread -- Any
Thread -- ThreadException

ThreadPool o-- CondVar
ThreadPool o-- Mutex
ThreadPool o-- SafeFifo
ThreadPool o-- ITask
ThreadPool o-- Thread

SafeFifo o-- Mutex
SafeFifo -- SafeFifo
SafeFifo -- ScopedMutex

Mutex ..|> IMutex
Mutex o-- CondVar

ScopedMutex o-- Mutex

@enduml