@startuml

title R-Type - Class Diagram

package std {
    Class std::exception
}

!include ECS-Classes.iuml
!include Network-Classes.iuml
!include Menu-Classes.iuml
!include NetworkRelay-Classes.iuml
!include Threads-Classes.iuml
!include Utility-Classes.iuml

'!include Components-Classes.iuml
'!include Systems-Classes.iuml

!include ECS-Links.iuml
!include Network-Links.iuml
!include Menu-Links.iuml
!include NetworkRelay-Links.iuml
!include Threads-Links.iuml

'!include Utility-Links.iuml

'!include Components-Links.iuml
'!include Systems-Links.iuml

@enduml